[package]
name = "phpms"
version = "0.1.0"
edition = "2021"
authors = ["Magnus Strömberg <magnus@magnus.tech>"]

[dependencies]
phper = "0.13.1"
geohash = "0.13.1"
haversine = "0.2.1"

[lib]
name = "phpms"
crate-type = ["lib", "cdylib"]
