version: '3.8'

services:
  php-fpm:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./target/release/libphpms.so:/usr/local/lib/php/extensions/no-debug-non-zts-20220829/libphpms.so
      - ./www:/var/www/html
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d:/usr/local/etc/php/extensions"
    command: >
      sh -c "echo 'extension=/usr/local/lib/php/extensions/no-debug-non-zts-20220829/libphpms.so' > /usr/local/etc/php/conf.d/phpms.ini && php-fpm"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm